export {default as Education} from './education'
export {default as JobDetails} from './jobDetails'
export {default as PageTitle} from './pageTitle'
export {default as ProgressBar} from './progressBar'
export {default as ServicesDetails} from './servicesDetails'
export {default as Feature} from './feature'

export type { PageTitleProps } from './pageTitle'
export type { ServicesDetailsProps } from './servicesDetails'
export type { ProgressBarProps } from './progressBar'
export type { JobDetailsProps } from './jobDetails'
export type { EducationProps } from './education'
export type { FeatureProps } from './feature'
